"""Added new column to model

Revision ID: 7c3ffbf8c4e4
Revises: 6edd7d005028
Create Date: 2024-10-08 10:27:22.996630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3ffbf8c4e4'
down_revision: Union[str, None] = '6edd7d005028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('role', sa.String(length=250), nullable=True))
    op.create_index(op.f('ix_user_tokens_role'), 'user_tokens', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tokens_role'), table_name='user_tokens')
    op.drop_column('user_tokens', 'role')
    # ### end Alembic commands ###
