"""Add statuspage_incident_id to Incident model

Revision ID: b48a72efa725
Revises: bb3a966e9547
Create Date: 2024-10-29 10:56:12.431993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48a72efa725'
down_revision: Union[str, None] = 'bb3a966e9547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_incidents', sa.Column('statuspage_incident_id', sa.String(length=250), nullable=True))
    op.create_unique_constraint(None, 'service_incidents', ['jira_issue_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_incidents', type_='unique')
    op.drop_column('service_incidents', 'statuspage_incident_id')
    # ### end Alembic commands ###
