"""Add jira_issue_key field to service_incidents table

Revision ID: bb3a966e9547
Revises: ea56a8fb050b
Create Date: 2024-10-23 10:40:29.246289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3a966e9547'
down_revision: Union[str, None] = 'ea56a8fb050b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_incidents', sa.Column('jira_issue_key', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_incidents', 'jira_issue_key')
    # ### end Alembic commands ###
