"""Add so_number as a new column to the Incident model

Revision ID: ea56a8fb050b
Revises: 7c3ffbf8c4e4
Create Date: 2024-10-16 10:48:21.617504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea56a8fb050b'
down_revision: Union[str, None] = '7c3ffbf8c4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_incidents', sa.Column('so_number', sa.String(length=250), nullable=True))
    op.create_index(op.f('ix_service_incidents_so_number'), 'service_incidents', ['so_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_incidents_so_number'), table_name='service_incidents')
    op.drop_column('service_incidents', 'so_number')
    # ### end Alembic commands ###
